version: '3'
services:
  web:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/code
    links:
     - db
    environment:
     - db=bfb14b76246c
     - db_port=27017
  db:
    image: mongo:3.0.2
  

  